### ISSUE TITLE
App crashed because AndroidManifest.xml contains Google Analytics receiver, which is not on classpath

### ISSUE THREAD

**Issue by alexxv** [AppsFlyerSDK/react-native-appsflyer#4]
Hey, 

I'm experiencing a crash, when receiving `INSTALL_REFERRER` intent.

```
12-05 14:12:35.079 16995 16995 E AndroidRuntime: java.lang.RuntimeException: 
Unable to instantiate receiver com.google.android.apps.analytics.AnalyticsReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.analytics.AnalyticsReceiver" on path: DexPathList[[zip file "/data/app/com.wondermall.prod-1/base.apk"],nativeLibraryDirectories=[/data/app/com.wondermall.prod-1/lib/arm, /system/fake-libs, /data/app/com.wondermall.prod-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2995)
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(ActivityThread.java)
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6088)
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
12-05 14:12:35.079 16995 16995 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.analytics.AnalyticsReceiver" on path: DexPathList[[zip file "/data/app/com.wondermall.prod-1/base.apk"],nativeLibraryDirectories=[/data/app/com.wondermall.prod-1/lib/arm, /system/fake-libs, /data/app/com.wondermall.prod-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2990)
12-05 14:12:35.079 16995 16995 E AndroidRuntime: 	... 8 more
```

The SDK's `AndroidManifest.xml` contains two receivers:
```
        <receiver android:name="com.google.android.apps.analytics.AnalyticsReceiver" android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.admob.android.ads.analytics.InstallReceiver" android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
```

One of them is not part of my app dependencies, this causes the crash.
Do you need those receivers? Can they be removed?

Thanks

Alex

**Comment by af-fess** [comment]
@alexxv  Please check  [AppsFlyer-SDK-Integration-Android](https://support.appsflyer.com/hc/en-us/articles/207032126-AppsFlyer-SDK-Integration-Android) section `2.3.1 Using a Multiple Broadcast Receiver`. Let me know if it helps you

**Comment by alexxv** [comment]
@af-fess same result. 
`MultipleBroadcastReceiver` or `SingleBroadcastReceiver` is not related here.
Do you really need those receivers in SDK's `AndroidManifest.xml`?
It looks like it can work without them, since the SDK does not depend on Google Analytics (which is where `com.google.android.apps.analytics.AnalyticsReceiver` comes from

**Comment by af-fess** [comment]
@alexxv right we will remove both receivers from Manifest. Anyways you can add these receivers to your host app Manifest and `com.google.android.gms` from `build.gradle`.

**Comment by af-fess** [comment]
removed dependency in 1.0.8

**Comment by iuraya** [comment]
Do I still need to declare an Install Referrer Broadcast Receiver in my Manifest in order to get Non-Organic Install?

**Comment by MaximShoustin** [comment]
yes, sure
